### ISSUE TITLE
자바 스터디

### ISSUE THREAD

**Issue by CreatiCoding** [CreatiCoding/KW_DS_Project#2]
1. 자료형 종류 조사
2. 출력 Hello World
3. 입력 정수 2개 입력 후 합 출력
4. 반복문으로 정사각형 별 찍기
5. 제어문으로 점수 입력하면 학점 출력 (90:A, 80:B, 70:C, 60:D, 그외 : F) 

@jimmy3663

**Comment by CreatiCoding** [comment]
자바 관련 사이트 https://wikidocs.net/book/31

**Comment by jimmy3663** [comment]
![image](https://user-images.githubusercontent.com/43136526/45309901-cbc4e800-b55f-11e8-9f30-9d18593c59be.png)
JRE system library가 default로 설정이 안되있네요. ㅠㅠ 
그래서 hello world 프린트 할때 System.out.println("hello word"); 로 했는데 System에서 에러가 나더라구요..
Description	Resource	Path	Location	Type
Unbound classpath container: 'JRE System Library [JavaSE-10]' in project 'SampleProject'	SampleProject		Build path	Build Path Problem
이렇게 나오는데 JRE System Library를 어떻게 bound 하죠..? 
인터넷에 보니까 그냥 자동으로 bound 되는거 같으데 ㅠㅠㅠㅠ

**Comment by CreatiCoding** [comment]
@jimmy3663  
http://mainia.tistory.com/3072
이거 한번 참고해봐 이클립스에서수동으로 jdk로 바꿀수 있어

**Comment by CreatiCoding** [comment]
@jimmy3663 
하다가 안되면
https://www.compilejava.net/
여기서 컴파일 해 ㅋㅋ 소스코드는 따로 보관하고

**Comment by jimmy3663** [comment]
넵 감사합니다. 다시 한번 해볼께요!

**Comment by CreatiCoding** [comment]
스터디 끝 굳굳
